# Copyright 2023 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "manage-external-guidance-frontend"
play.http.router  = prod.Routes

play.filters.enabled += play.filters.csp.CSPFilter

play.filters.enabled += "filters.ShutterFilter"

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Custom error handler
play.http.errorHandler = "config.ErrorHandler"

# Play Modules
# ~~~~
# Additional play modules can be added here
play.modules.enabled += "config.Module"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"

play.http.session.secure = false

# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
# Not set here so that MDTP frontends share the same secret key in the local environment
# (see common.conf in frontend-bootstrap).
# In server environments the secret comes from app-config-common
# play.crypto.secret="YvvlQF4R2o7oQLrkAKN1Kdd1L142NkbRfvBTksXHQZXRRfaTUbSN1mJj44nsGmJt"

host = "http://localhost:9740"

microservice {
  metrics {
    graphite.enabled = true
  }

  services {

    auth {
      host = localhost
      port = 8500
    }

    contact-frontend {
      protocol = http
      host = localhost
      port = 9250
    }

    external-guidance {
      host = localhost
      port = 9742
    }

  }
}

urls {
  baseUrl = "/guidance"
  externalGuidanceScratchUrl = "/external-guidance/scratch"
  externalGuidanceApprovalUrl = "/external-guidance/approval"
}

external-guidance-viewer {
  host = "http://localhost:9741"
  api-host = "http://localhost:9741"
  adminBaseUrl = "/review-guidance"
  approvalUrl = "/approval"
  publishedUrl = "/published"
  pageMapApprovalUrl = "/map-approval"
  pageMapPublishedUrl = "/map-published"
  activeProcessesUrl = "/active"
}

strideAuth {
  login{
    url = "http://localhost:9041/stride/sign-in"
    continueUrl = "/external-guidance"
    timescalesContinueUrl = "/external-guidance/timescales"
    ratesContinueUrl = "/external-guidance/rates"
    designerAdminContinueUrl = "/external-guidance/designer"
    processAdminContinueUrl = "/external-guidance/admin"
  }
  roles {
    designer = Designer
    twoEyeReviewer = 2iReviewer
    factChecker = FactChecker
  }
}

appLinks {
   # Place holder url until correct url is available
   commentsAndFeedbackUrl = "http://www.gov.uk"
}

contact-frontend-urls {
  serviceIdentifier = "EGADM"
  reportAProblemNonJSUrl = "/contact/problem_reports_nonjs?service="${contact-frontend-urls.serviceIdentifier}
}

shuttered = false

play.http.parser.maxMemoryBuffer=1024K

admin-username: admin
admin-password: password
